```{r libraries, error=FALSE, message=FALSE,   echo=FALSE, cache=FALSE, warning=FALSE}
library(dplyr)
library(semanticaxelrod)
library(ggplot2)

load("~/local-research/semanticaxelrod/rawdata/saa12-final.rda")


saa12finalnoinnov <- subset(saa12final, innovation_rate == 0 )
saa12finalinnov <- subset(saa12final, innovation_rate > 0 )

```

## Lambda ##

Without innovation:

```{r lambda-noinnov, results="asis", message=FALSE, warning=FALSE, fig.width=12}

p <- ggplot(saa12finalnoinnov, aes(x=msg_lambda)) + geom_density(fill="red")
p + facet_grid(learning_rate ~ size_trait_space, scale="free_y")

```

And with innovation:

```{r lambda-innov, results="asis", message=FALSE, warning=FALSE, fig.width=12}

p <- ggplot(saa12finalinnov, aes(x=msg_lambda)) + geom_density(fill="red")
p + facet_grid(learning_rate ~ size_trait_space, scale="free_y")

```

## Radius ##


Without innovation:

```{r radius-noinnov, results="asis", message=FALSE, warning=FALSE, fig.width=12}

p <- ggplot(saa12finalnoinnov, aes(x=radius_frac)) + geom_density(fill="red")
p + facet_grid(learning_rate ~ size_trait_space, scale="free_y")

```

And with innovation:

```{r radius-innov, results="asis", message=FALSE, warning=FALSE, fig.width=12}

p <- ggplot(saa12finalinnov, aes(x=radius_frac)) + geom_density(fill="red")
p + facet_grid(learning_rate ~ size_trait_space, scale="free_y")

```

## Mean Degree ##

Without innovation:

```{r degree-noinnov, results="asis", message=FALSE, warning=FALSE, fig.width=12}

p <- ggplot(saa12finalnoinnov, aes(x=mean_degree)) + geom_density(fill="red")
p + facet_grid(learning_rate ~ size_trait_space, scale="free_y")

```

And with innovation:

```{r degree-innov, results="asis", message=FALSE, warning=FALSE, fig.width=12}

p <- ggplot(saa12finalinnov, aes(x=mean_degree)) + geom_density(fill="red")
p + facet_grid(learning_rate ~ size_trait_space, scale="free_y")

```



