```{r libraries, error=FALSE, message=FALSE,   echo=FALSE, cache=FALSE, warning=FALSE}
library(dplyr)
library(semanticaxelrod)
library(ggplot2)

load("~/local-research/semanticaxelrod/rawdata/saa34-full.rda")


saa34finalnoinnov <- subset(saa34full, innovation_rate == 0 )
saa34finalinnov <- subset(saa34full, innovation_rate > 0 )

```

## Orbit Number and |Aut(G)|:  How Much Symmetry? ##

Without innovation:

```{r orbits-noinnov, results="asis", message=FALSE, warning=FALSE, fig.width=12}

p <- ggplot(saa34finalnoinnov, aes(x=orbit_number)) + geom_density(fill="red")
p + facet_grid(learning_rate ~ size_trait_space, scale="free_y",as.table=FALSE)

```

And with innovation:

```{r orbits-innov, results="asis", message=FALSE, warning=FALSE, fig.width=12}

p <- ggplot(saa34finalinnov, aes(x=orbit_number)) + geom_density(fill="red")
p + facet_grid(learning_rate ~ size_trait_space, scale="free_y",as.table=FALSE)

```

Aut(g) first without innovation:

```{r autg-noinnov, results="asis", message=FALSE, warning=FALSE, fig.width=12}

p <- ggplot(saa34finalnoinnov, aes(x=log(autgroupsize))) + geom_density(fill="red")
p + facet_grid(learning_rate ~ size_trait_space, scale="free_y",as.table=FALSE)

```

And with innovation:

```{r autg-innov, results="asis", message=FALSE, warning=FALSE, fig.width=12}

p <- ggplot(saa34finalinnov, aes(x=log(autgroupsize))) + geom_density(fill="red")
p + facet_grid(learning_rate ~ size_trait_space, scale="free_y",as.table=FALSE)

```



