```{r libraries, error=FALSE, message=FALSE,   echo=FALSE, cache=FALSE, warning=FALSE}
library(dplyr)
library(semanticaxelrod)
library(ggplot2)
library(grid)

theme_set(theme_bw())


load("~/local-research/semanticaxelrod/rawdata/saa12-full.rda")

saa12fullnoinnov <- subset(saa12full, innovation_rate == 0 )
saa12fullinnov <- subset(saa12full, innovation_rate > 0 )

saa12highinnov <- subset(saa12full, innovation_rate == 5e-05)


# subset of data for the conference presentation

cf <- subset(saa12full, size_trait_space == 160 | size_trait_space == 640 | size_trait_space == 2496 | size_trait_space == 62496 )
confsubset <- subset(cf, learning_rate == 0.1 | learning_rate == 0.4 | learning_rate == 0.9)


```

# Density Plots #

```{r radius-1, results="asis", message=FALSE, warning=FALSE, highlight=TRUE, fig.width=12}

p <- ggplot(data=saa12full, aes(y=remaining_density, x=factor(learning_rate), fill=factor(innovation_rate))) + ylab("Normalized Trait Tree Size") + xlab("Prerequisite Learning Rate") + labs(fill="Global Innovation Rate")
p + geom_boxplot(notch=FALSE)

```


```{r orbit-1, results="asis", message=FALSE, warning=FALSE, highlight=TRUE, fig.width=8}
p <- ggplot(data=saa12full, aes(x=log(autgroupsize))) + xlab("Number of Symmetries in Culture Samples log |Aut(g)|") + geom_density(fill="darkgrey")
p + facet_grid(learning_rate ~ ., as.table=FALSE)
```


```{r orbit-2, results="asis", message=FALSE, warning=FALSE, highlight=TRUE, fig.width=12}
p <- ggplot(data=saa12full, aes(x=log(autgroupsize))) + xlab("Number of Symmetries in Culture Samples log |Aut(g)|") + geom_density(fill="darkgrey")
p + facet_grid(learning_rate ~ innovation_rate, as.table=FALSE)
ggsave("../paper/figure/autgroupsize-by-learning-by-innovation.pdf", dpi=300)
```

```{r orbit-3, results="asis", message=FALSE, warning=FALSE, highlight=TRUE, fig.width=12}
p <- ggplot(data=saa12highinnov, aes(x=log(autgroupsize))) + xlab("Number of Symmetries in Culture Samples log |Aut(g)|") + geom_density(fill="darkgrey")
p + facet_grid(learning_rate ~ size_trait_space, as.table=FALSE)
#ggsave("../paper/figure/autgroupsize-by-learning-by-innovation.pdf", dpi=300)
```
